### ISSUE TITLE
[Bug] The Changelog page does not load.

### ISSUE THREAD

**Issue by xXFreeFunXx** [mue/mue#517]
![](https://cdn.discordapp.com/attachments/1106326089569148999/1165411199098302575/zR2MI3Hb4f.png?ex=6546c0c2&is=65344bc2&hm=9887bcf3c3ad3abdb87d07c0672882b54101a4781209281f3dd86f4841cd58ea&)

**Comment by eartharoid** [comment]
This worked before we released 7.0.
It's fetching https://blog.muetab.com/posts/version-7-0/index.json, which is apparently hardcoded:
https://github.com/mue/mue/blob/90110ec6cdea837cfeba992aa4506bbbe6c93263/src/modules/constants.js#L12

It seems this error isn't a bug, it's caused by that URL not existing because we forgot to write the changelog (the blog has been offline for a long time and was only fixed relatively recently).

**Comment by davidcralph** [comment]
Changelog no longer relies on the blog, so this can be closed
