### ISSUE TITLE
[Bug] Quote author image license text

### ISSUE THREAD

**Issue by eartharoid** [mue/mue#549]
**Description**

The copyright text sometimes has a link:

**To Reproduce**

Enable the quote widget and refresh the page until you see it

**Expected behaviour**

Look nice

**Screenshots**

![image](https://github.com/mue/mue/assets/20905071/8b127c20-82e0-48fe-896d-3f0521f3db29)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - Browser: Firefox
 - Browser Version: 119
 - Mue Version: 7.0
 - Resolution: N/A

**Additional context**

**Comment by partha51613** [comment]
The image of Steve Jobs is clicked by a user named 'Matt Yohe" (src: https://en.wikipedia.org/wiki/Steve_Jobs#/media/File:Steve_Jobs_Headshot_2010-CROP_(cropped_2).jpg )

![image](https://github.com/mue/mue/assets/23007104/ced47700-a4bf-4653-98be-d0777718f26b)

I think the issue is in this file : **src/components/widgets/quote/Quote.jsx**
The regex used by **authorimglicense** is not able to filter the author value fetched by the API
